# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='null', max_length=55),
        ),
    ]
